server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/cache_example?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000

  rabbitmq: # 如果使用 RabbitMQ
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: auto

logging:
  level:
    com.yetcache.*: debug

yetcache:
  global:
    spec:
      cache-tier: BOTH
      tenant-mode: NONE
      use-hash-tag: true
    kv:
      local:
        ttl-secs: 300
        ttl-random-pct: 0.1
        penetration-protect:
          enabled: true
          ttl-secs: 30
          max-size: 10000
      remote:
        ttl-secs: 600
        ttl-random-pct: 0.1
        penetration-protect:
          enabled: true
          ttl-secs: 60
          max-size: 10000
  caches:
    kv:
      user-id-key-cache:
        spec:
          cache-name: 'user-id-key-cache'
          key-prefix: 'nd:acc:user:idk'
          tenant-mode: NONE
          cache-tier: BOTH
          use-hash-tag: true
        local:
          max-size: 2000
          ttl-secs: 30
          ttl-random-pct: 0.1
          penetration-protect:
            enabled: true
            ttl-secs: 30
            max-size: 10000
        remote:
          ttl-secs: 120
          ttl-random-pct: 0.1
          penetration-protect:
            enabled: true
            ttl-secs: 60
            max-size: 10000

