server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/cache_example?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000

  rabbitmq:  # 如果使用 RabbitMQ
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: auto

common:
  cache-agent:
    user:
      id: 'USER_CACHE_AGENT'
      key-prefix: 'yc:exam:user'
      tenant-check-level: 'NONE'
      redis-cache-enabled: true
      caffeine-expire-secs: 3
    stock-hold-info:
      id: 'STOCK_HOLD_INFO_CACHE_AGENT'
      key-prefix: 'yc:exam:stock-hold-info'
      tenant-check-level: 'NONE'
      redis-cache-enabled: true
      caffeine-expire-secs: 3